config/routes.rb
Rails.application.routes.draw do
  # EndUser
  devise_for :end_users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  devise_scope :end_user do
    get "end_users/:id/edit" => "public/registrations#edit", as: :edit_other_end_user_registration
    match "end_users/:id", to: "public/registrations#update", via: [:patch], as: :other_end_user_registaration
  end

  scope module: :public do
    root to: "homes#top"
    resources :daily_reports, only: [:new, :create] do
      collection do
        get :thank_you
      end
    end
  end

  # 管理者
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: "homes#top"
    resources :cars, only: [:new, :create, :index, :edit, :update]
    resources :end_users, only: [:index, :edit, :update]
    resources :companies, only: [:new, :create, :index, :show, :edit, :update]
    resources :constructions, only: [:index, :show, :new, :create, :edit, :update] do
      collection do
        get :constructions_index
      end
      member do
        get :end_users_index
      end
    end
    
    resources :daily_reports, only: [:new, :create, :show, :edit, :update] do
      member do
        get :image
      end
    end
    
    resources :work_schedules, only: [:new, :create, :index, :show]

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
    has_many :daily_reports, dependent: :destroy
    
    validates :number, presence: true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :daily_reports, dependent: :destroy
  
  enum deadline: { "10日": 0, "15日": 1, "20日": 2, "25日": 3, 末日: 4, 都度: 5 }
  
  validates :company_name, presence: true
end

app/models/construction.rb
class Construction < ApplicationRecord
  has_many :daily_reports, dependent: :destroy
  
  validates :construction_name, presence: true
end

app/models/daily_report.rb
class DailyReport < ApplicationRecord
  belongs_to :end_user
  belongs_to :company
  belongs_to :construction
  belongs_to :car
  belongs_to :work_schedule
    
  has_many_attached :daily_report_images
  
  validates :date, presence: true
  
  enum weather: { 晴れ: 0, くもり: 1, 雨: 2, 雪: 3 }
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :daily_reports, dependent: :destroy
  has_many :work_schedules, dependent: :destroy
  
    def update_without_password(params, *options)
    # current_password = params.delete(:current_password)

    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end

    # result = if valid_password?(current_password)
    #   update_attributes(params, *options)
    # else
    #   self.assign_attributes(params, *options)
    #   self.valid?
    #   self.errors.add(:current_password, current_password.blank? ? :blank : :invalid)
    #   false
    # end

    update_attributes(params, *options)

    clean_up_passwords
    result
  end
  
end

app/models/role.rb
class Role < ApplicationRecord

end

app/models/work_schedule.rb
class WorkSchedule < ApplicationRecord
  belongs_to :end_user
  has_many :daily_reports, dependent: :nullify
  
  validates :date, presence: true
end

app/controllers/admin/cars_controller.rb
class Admin::CarsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    if @car.save
      redirect_to admin_cars_path
    else
      render "new"
    end
  end
  
  def index
    @cars = Car.page(params[:page])
  end
  
  def edit
    @car = Car.find(params[:id])
  end
  
  def update
    @car = Car.find(params[:id])
    if @car.update(car_params)
      redirect_to admin_cars_path
    else
      render "edit"
    end
  end

  private

  def car_params
    params.require(:car).permit(:number, :use)
  end
end

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < ApplicationController
    before_action :authenticate_admin!
    
  def index
    @end_users = EndUser.page(params[:page])
  end
  
  def edit
    @end_user = EndUser.find(params[:id])
  end

  def update
    @end_user = EndUser.find(params[:id])
    if @end_user.update(end_user_params)
        redirect_to admin_end_users_path
    else
       render "edit"
    end
  end
  
  private
  
  def end_user_params
    params.require(:end_user).permit(:name, :email, :retirement, :password)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
    @daily_reports = DailyReport.where(check: false)
    @daily_reports = @daily_reports.order(date: "DESC").page(params[:page])
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  
  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
  
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/cars_helper.rb
module Admin::CarsHelper
end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
end

app/helpers/admin/constructions_helper.rb
module Admin::ConstructionsHelper
end

app/helpers/admin/daily_reports_helper.rb
module Admin::DailyReportsHelper
end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/work_schedules_helper.rb
module Admin::WorkSchedulesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/end_users/edit.html.erb
<%= render "layouts/error", resource: @end_user %>

<h2 class="heading">社員編集</h2>

<%= form_with model: @end_user, url: admin_end_user_path(@end_user), local: false do |f| %>
  <table>
    <tr>
      <th><%= f.label :名前 %></th>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <th><%= f.label :メールアドレス %></th>
      <td><%= f.text_field :email %></td>
    </tr>
    <tr>
      <th><%= f.label :パスワード %></th>
      <td><%= f.text_field :password %><span class="text__red">※必須</span></td>
    </tr>
    <tr>
      <th><%= f.label :ステータス %></th>
      <td>
        <%= f.radio_button :retirement, false %>
        <%= f.label :ステータス, "在籍中", value: false %>
        <%= f.radio_button :retirement, true %>
        <%= f.label :ステータス, "退職", value: true %>
      </td>
    </tr>
  </table>
  <div class="btn">
    <%= f.submit "変更を保存", class: "btn__green" %>
  </div>
<% end %>

app/views/admin/end_users/index.html.erb
<h2 class="heading">社員一覧</h2>

<div class="link">
  <%= link_to "社員登録", new_end_user_registration_path, class: "link__green" %>
</div>

<table class="table">
  <thead class="table__heading">
    <tr class="table__row">
      <th class="table__item">社員名</th>
      <th class="table__item">ステータス</th>
      <th class="table__item"></th>
    </tr>
  </thead>

  <tbody>
    <% @end_users.each do |end_user| %>
    <tr class="table__row">
      <td class="table__item"><%= end_user.name %></td>
      <td class="table__item">
        <% if end_user.retirement == false %>
          <span>在籍中</span>
        <% else %>
          <span>退職</span>
        <% end %>
      </td>
      <td class="table__item">
        <% if current_admin %>
          <%= link_to "編集", edit_admin_end_user_path(end_user) %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="link__paginate">
  <%= paginate @end_users %>
</div>