config/routes.rb
Rails.application.routes.draw do
  # EndUser
  devise_for :end_users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  devise_scope :end_user do
    get "end_users/:id/edit" => "public/registrations#edit", as: :edit_other_end_user_registration
    match "end_users/:id", to: "public/registrations#update", via: [:patch], as: :other_end_user_registaration
  end

  scope module: :public do
    root to: "homes#top"
    resources :daily_reports, only: [:new, :create] do
      collection do
        get :thank_you
      end
    end
  end

  # 管理者
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: "homes#top"
    resources :cars, only: [:new, :create, :index, :edit, :update]
    resources :end_users, only: [:index, :edit, :update]
    resources :companies, only: [:new, :create, :index, :show, :edit, :update]
    resources :constructions, only: [:index, :show, :new, :create, :edit, :update] do
      collection do
        get :constructions_index
      end
      member do
        get :end_users_index
      end
    end
    
    resources :daily_reports, only: [:new, :create, :show, :edit, :update] do
      member do
        get :image
      end
    end
    
    resources :work_schedules, only: [:new, :create, :index, :show]

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
    has_many :daily_reports, dependent: :destroy
    
    validates :number, presence: true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :daily_reports, dependent: :destroy
  
  enum deadline: { "10日": 0, "15日": 1, "20日": 2, "25日": 3, 末日: 4, 都度: 5 }
  
  validates :company_name, presence: true
end

app/models/construction.rb
class Construction < ApplicationRecord
  has_many :daily_reports, dependent: :destroy
  
  validates :construction_name, presence: true
end

app/models/daily_report.rb
class DailyReport < ApplicationRecord
  belongs_to :end_user
  belongs_to :company
  belongs_to :construction
  belongs_to :car
  belongs_to :work_schedule
    
  has_many_attached :daily_report_images
  
  validates :date, presence: true
  
  enum weather: { 晴れ: 0, くもり: 1, 雨: 2, 雪: 3 }
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :daily_reports, dependent: :destroy
  has_many :work_schedules, dependent: :destroy
  
    def update_without_password(params, *options)
    # current_password = params.delete(:current_password)

    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end

    # result = if valid_password?(current_password)
    #   update_attributes(params, *options)
    # else
    #   self.assign_attributes(params, *options)
    #   self.valid?
    #   self.errors.add(:current_password, current_password.blank? ? :blank : :invalid)
    #   false
    # end

    update_attributes(params, *options)

    clean_up_passwords
    result
  end
  
end

app/models/role.rb
class Role < ApplicationRecord

end

app/models/work_schedule.rb
class WorkSchedule < ApplicationRecord
  belongs_to :end_user
  has_many :daily_reports, dependent: :nullify
  
  validates :date, presence: true
end

app/controllers/admin/cars_controller.rb
class Admin::CarsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    if @car.save
      redirect_to admin_cars_path
    else
      render "new"
    end
  end
  
  def index
    @cars = Car.page(params[:page])
  end
  
  def edit
    @car = Car.find(params[:id])
  end
  
  def update
    @car = Car.find(params[:id])
    if @car.update(car_params)
      redirect_to admin_cars_path
    else
      render "edit"
    end
  end

  private

  def car_params
    params.require(:car).permit(:number, :use)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
    @daily_reports = DailyReport.where(check: false)
    @daily_reports = @daily_reports.order(date: "DESC").page(params[:page])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/cars_helper.rb
module Admin::CarsHelper
end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
end

app/helpers/admin/constructions_helper.rb
module Admin::ConstructionsHelper
end

app/helpers/admin/daily_reports_helper.rb
module Admin::DailyReportsHelper
end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/work_schedules_helper.rb
module Admin::WorkSchedulesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_error.html.erb
<% if resource.errors.any? %>
  <div class="alert">
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <p class="footer__text">Copyright © 2022 nipo All Rights Reserved.</p>
</footer>
  

app/views/layouts/_header.html.erb
<header class="header">
  <div class="header__logo"></div>
  <ul class="header__link">
    <!--end_userログイン後-->
    <% if end_user_signed_in? %>
      <li class="header__link--item">
        <%= link_to "ログアウト", destroy_end_user_session_path, method: :delete, class: "header__link--item" %>
      </li>
      
    <!--adminログイン後-->
    <% elsif admin_signed_in? %>
      <li clas="header__link--item">
        <%= link_to "ホーム", admin_root_path, class: "header__link--item" %>
      </li>
      <li class="header__link--item">
        <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "header__link--item" %>
      </li>
    <% end %>
  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nipo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <main>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>